// src/views/monitor/redis/components/CommandStatsChart.vue
<template>
  <a-card title="命令统计">
    <div
      id="main"
      ref="echartsRef"
      class="echarts"
      :style="{
        height: '300px',
      }"
    ></div>
  </a-card>
</template>

<script lang="ts">
  import { defineComponent, onMounted, watch, toRaw } from 'vue';
  import * as echarts from 'echarts';

  export default {
    name: 'CommandStatsChart',
    props: {
      commandStats: {},
    },
    setup(props) {
      let barChart;

      watch(
        () => props.commandStats,
        (newValue, oldValue) => {
          const commandStats = toRaw(newValue);
          barChart.setOption({
            tooltip: {
              trigger: 'item',
              formatter: '{a} <br/>{b} : {c} ({d}%)',
            },
            legend: {
              left: 'center',
              bottom: '10',
            },
            series: [
              {
                name: '命令统计',
                type: 'pie',
                roseType: 'radius',
                radius: [15, 95],
                center: ['50%', '38%'],
                data: commandStats,
                animationEasing: 'cubicInOut',
                animationDuration: 2600,
              },
            ],
          });
        },
        {
          // 必须开启深度才有获取到旧数据
          deep: true,
        }
      );

      onMounted(() => {
        barChart = echarts.init(document.getElementById('main') as HTMLElement);
      });
    },
  };
</script>

// src/pages/monitor/redis/components/CommandStatsChart.tsx
import { useEffect } from 'react'
import * as echarts from 'echarts/lib/echarts.js'
import 'echarts/lib/chart/bar'
import 'echarts/theme/macarons'
import styles from './styles.less'
import React from 'react'
import { Card } from 'antd'

/**
 * 扇形图
 */
const CommandStatsChart: React.FC<{ commandStats: {} | undefined }> = (props) => {

    let commandStatsChart: HTMLDivElement;

    const { commandStats } = props

    // 第一次渲染时执行
    useEffect(() => {
        // 获取echarts实例
        const instance: any = echarts.init(commandStatsChart)
        // 开启自适应
        window.addEventListener('resize', instance.resize)

        // 设置参数
        instance.setOption({
            tooltip: {
                trigger: 'item',
                formatter: '{a} <br/>{b} : {c} ({d}%)'
            },
            legend: {
                left: 'center',
                bottom: '10',
            },
            series: [
                {
                    name: '命令统计',
                    type: 'pie',
                    roseType: 'radius',
                    radius: [15, 95],
                    center: ['50%', '38%'],
                    data: commandStats,
                    animationEasing: 'cubicInOut',
                    animationDuration: 2600
                }
            ]
        })

        // 关闭监听
        return () => {
            window.removeEventListener('resize', instance.resize)
        }

    }, [commandStats])

    return (
        <Card title="命令统计">
            <div
                ref={(ref: HTMLDivElement) => commandStatsChart = ref}
                className={styles.commandStatsChart}
            >
            </div>
        </Card>

    )

}

export default CommandStatsChart
